%YAML:1.0
# 注意本文件内不要出现 Tab 字符

# KITTI 数据集路径，请保证结尾无"/"字符
dataset_dir: /media/vance/00077298000E1760/dataset/KITTI/sequences
# KITTI 数据集序号，取01-12,请保证以"/"开头
sequence_num: /03

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
# 相机内参
Camera.fx: 721.5377
Camera.fy: 721.5377
Camera.cx: 609.5593
Camera.cy: 172.854
# 畸变参数
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
# 图像尺寸
Camera.width: 1241
Camera.height: 376
# 每秒处理帧数
Camera.fps: 10.0
# 相机基线与fx的乘积，bf=b*fx
Camera.bf: 387.5744

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# 每副图像要提取的特征点数量
ORB.nFeatures: 2000
# 金字塔缩放尺度
ORB.scaleFactor: 1.2
# 金字塔层数
ORB.pyramidLevels_: 8

#--------------------------------------------------------------------------------------------
# VO Parameters
#--------------------------------------------------------------------------------------------
 # 选最小距离的2倍作为特征点描述子的匹配距离阈值
match_ratio: 2
# 最大连续丢失帧数
max_num_lost: 20
# PnP最小局内点
min_inliers: 20
# 当前局内点与当前局部地图点数的最小比率，低于这个比率的帧跳过
min_ratio: 0.5
# 成为关键帧的最小旋转量
keyframe_rotation: 0.1
# 成为关键帧的最小平移量
keyframe_translation: 0.1
# MapPoint的 匹配次数/观测次数 比值，小于这个比值的MapPoint的将会被剔除
map_point_erase_ratio: 0.1
# 是否要显示左右图像的匹配情况
view_matches: 1


