%YAML:1.0

# the kitti dataset directory, change it to yours! 
dataset_dir: /media/vance/00077298000E1760/dataset/KITTI/sequences/05

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 707.0912
Camera.fy: 707.0912
Camera.cx: 601.8873
Camera.cy: 183.1104

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1241
Camera.height: 376

Camera.fps: 10.0        # Camera frames per second 
Camera.bf: 379.8145     # stereo baseline times fx

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORB.nFeatures: 2000     # ORB Extractor: Number of features per image
ORB.scaleFactor: 1.2    # ORB Extractor: Scale factor between levels in the scale pyramid 	
ORB.pyramidLevels_: 8          # ORB Extractor: Number of levels in the scale pyramid
		
#--------------------------------------------------------------------------------------------
# VO Parameters
#--------------------------------------------------------------------------------------------
match_ratio: 1.5            # 选最小距离的2倍作为特征点描述子的匹配距离阈值
max_num_lost: 20            # 最大连续丢失帧数
min_inliers: 15             # 最小匹配局内点数
keyframe_rotation: 0.1      #
keyframe_translation: 0.1   # 
map_point_erase_ratio: 0.1  # MapPoint的 匹配次数/观测次数 比值，小于这个比值的MapPoint的将会被剔除
viewer_matches:1            # 是否要显示左右图像的匹配情况
